### ISSUE TITLE
DataParser release

### ISSUE THREAD

**Issue by code-creater** [Calculator88/sesc-tool#2]
# Description
To the first version of DataParser library we need to add electronic journal and supporting of getting all types of static schedule.<br/><br/>
# TODO
- [ ] Timetable:
  - [ ] One class timetable.
  - [ ] Classroom's employment.
  - [ ] One teacher schedule.
  - [ ] One classroom timetable.
- [ ] Electronic journal:
  - [ ] Authentication [here](http://lyceum.urfu.ru/register).
  - [ ] Marks for one month. 
  - [ ] Results.
