### ISSUE TITLE
Allow serialization

### ISSUE THREAD

**Issue by AlexHurt** [Calculator88/sesc-tool#6]
# Description
Allow Add serialization to certain classes to quickly save to file
# TODO-list
- [ ] Serializtion:
  - [ ] One class timetable.
  - [ ] Classroom's employment.
  - [ ] One teacher schedule.
  - [ ] One classroom timetable.
